# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_sop_cov_cpp <- function(m1, vl1, nu, phi, kappa, psi, q) {
    .Call('_hhh4underreporting_compute_sop_cov_cpp', PACKAGE = 'hhh4underreporting', m1, vl1, nu, phi, kappa, psi, q)
}

reparam_cov_cpp <- function(m1, vl1, nu, phi, kappa, psi, q) {
    .Call('_hhh4underreporting_reparam_cov_cpp', PACKAGE = 'hhh4underreporting', m1, vl1, nu, phi, kappa, psi, q)
}

get_weight_matrix_cov_cpp <- function(phi, kappa, max_lag) {
    .Call('_hhh4underreporting_get_weight_matrix_cov_cpp', PACKAGE = 'hhh4underreporting', phi, kappa, max_lag)
}

nu_to_nu_star_cov_cpp <- function(nu, kappa) {
    .Call('_hhh4underreporting_nu_to_nu_star_cov_cpp', PACKAGE = 'hhh4underreporting', nu, kappa)
}

nllik_cov_cpp <- function(Y, m1, vl1, nu, phi, kappa, psi, q, max_lag = 5L) {
    .Call('_hhh4underreporting_nllik_cov_cpp', PACKAGE = 'hhh4underreporting', Y, m1, vl1, nu, phi, kappa, psi, q, max_lag)
}

back_seas_cpp <- function(vect, to, lgt) {
    .Call('_hhh4underreporting_back_seas_cpp', PACKAGE = 'hhh4underreporting', vect, to, lgt)
}

get_weight_matrix_seas_cpp <- function(phi, kappa, max_lag) {
    .Call('_hhh4underreporting_get_weight_matrix_seas_cpp', PACKAGE = 'hhh4underreporting', phi, kappa, max_lag)
}

prod <- function(vect) {
    .Call('_hhh4underreporting_prod', PACKAGE = 'hhh4underreporting', vect)
}

order_back_in_time <- function(vect, from) {
    .Call('_hhh4underreporting_order_back_in_time', PACKAGE = 'hhh4underreporting', vect, from)
}

stat_mean_seas_cpp <- function(nu, phi, kappa) {
    .Call('_hhh4underreporting_stat_mean_seas_cpp', PACKAGE = 'hhh4underreporting', nu, phi, kappa)
}

stat_var_seas_cpp <- function(nu, phi, kappa, psi) {
    .Call('_hhh4underreporting_stat_var_seas_cpp', PACKAGE = 'hhh4underreporting', nu, phi, kappa, psi)
}

nu_to_nu_star_seas_cpp <- function(nu, kappa, max_lag) {
    .Call('_hhh4underreporting_nu_to_nu_star_seas_cpp', PACKAGE = 'hhh4underreporting', nu, kappa, max_lag)
}

compute_sop_seas_cpp <- function(nu, phi, kappa, psi, q) {
    .Call('_hhh4underreporting_compute_sop_seas_cpp', PACKAGE = 'hhh4underreporting', nu, phi, kappa, psi, q)
}

reparam_seas_cpp <- function(nu, phi, kappa, psi, q) {
    .Call('_hhh4underreporting_reparam_seas_cpp', PACKAGE = 'hhh4underreporting', nu, phi, kappa, psi, q)
}

get_mod_matr_cpp <- function(observed, max_lag) {
    .Call('_hhh4underreporting_get_mod_matr_cpp', PACKAGE = 'hhh4underreporting', observed, max_lag)
}

